workflow:
  name: shopping-app
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_MERGE_REQUEST_ID'
      when: always

stages:
  - ".pre"
  - test
  - build
  - integration
  - deploy
  - ".post"

variables:
  # No DOCKER_HOST needed for self-hosted runner with Docker
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  LATEST_TAG: "$CI_REGISTRY_IMAGE:latest"
  APP_IMG_NAME: "google-adk"

lint_job:
  stage: ".pre"
  resource_group: development
  tags:
    - shopping_app
  script:
    - echo "Running linting checks..."
    - echo "Lint Successful"
  allow_failure: false

unit_test_job:
  stage: test
  variables:
    ENV_FILE_DESTINATION: "/workspace/multi_tool_agent/.env"
  tags:
    - shopping_app
  needs:
    - lint_job
  resource_group: development
  script:
    - echo "Running unit tests..."
    
    # Check Docker is available
    - docker --version
    - docker info
    
    # Prepare environment file
    - mkdir -p "$(dirname "$ENV_FILE_DESTINATION")"
    - cp "$AGENT_ENV_FILE" "$ENV_FILE_DESTINATION" || echo "No env file to copy"
    
    # Build the image
    - docker build -t "$APP_IMG_NAME:test" .
    
    # Run basic container test (don't bind ports in CI)
    - docker run --rm --name "${APP_IMG_NAME}_test_instance" "$APP_IMG_NAME:test" python --version
    
    # Test API server startup (background process)
    - |
      docker run -d --rm \
        --name "${APP_IMG_NAME}_api_test" \
        -p "8000:8000" \
        "$APP_IMG_NAME:test" \
        bash -c "adk api_server --host=0.0.0.0"
    
    # Wait and test API
    - sleep 15
    - curl -f http://localhost:8000/docs/ || echo "API docs not accessible"
    - docker stop "${APP_IMG_NAME}_api_test" || true
    
    - echo "Unit tests completed"
  allow_failure: false

mongodb_test_job:
  stage: test
  tags:
    - shopping_app
  needs:
    - lint_job
  resource_group: development
  script:
    - echo "Testing MongoDB connectivity..."
    
    # Check Docker is available
    - docker --version
    
    # Start MongoDB container
    - docker run --rm --name mongodb-test -d -p 27017:27017 mongo:latest
    - sleep 15
    
    # Test MongoDB connectivity
    - docker exec mongodb-test mongosh --eval "db.runCommand({ ping: 1 })" || echo "MongoDB ping failed"
    
    # Cleanup
    - docker stop mongodb-test || true
    - echo "MongoDB test completed"
  allow_failure: false