workflow:
  name: shopping-app
  rules:
    - if: '$CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "main"'
      when: always
    - if: '$CI_MERGE_REQUEST_ID'
      when: always

stages:
  - ".pre"
  - test
  - build
  - integration
  - deploy
  - ".post"

variables:
  # No DOCKER_HOST needed for self-hosted runner with Docker
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  LATEST_TAG: "$CI_REGISTRY_IMAGE:latest"
  APP_IMG_NAME: "google-adk"

lint_job:
  stage: ".pre"
  resource_group: development
  tags:
    - shopping_app
  script:
    - echo "Running linting checks..."
    - echo "Lint Successful"
  allow_failure: false

unit_test_job:
  stage: test
  variables:
    ENV_FILE_DESTINATION: "/workspace/multi_tool_agent/.env"
  tags:
    - shopping_app
  needs:
    - lint_job
  resource_group: development
  script:
    - echo "Running job as ${whoami}"
    - echo "Setting Up Curl..."
    - apk add --no-cache curl
    # Check Docker is available
    - docker --version
    - docker info
    
    # Prepare environment file
    - mkdir -p "$(dirname "$ENV_FILE_DESTINATION")"
    - cp "$AGENT_ENV_FILE" "$ENV_FILE_DESTINATION" || echo "No env file to copy"
    
    # Build the image
    - test -n "$(docker images -q "$APP_IMG_NAME")" || docker build -t "$APP_IMG_NAME:test" .

    # Option 2: Use docker exec to test inside container
    - echo "Testing API server with docker exec..."
    - docker run -d --rm --name "${APP_IMG_NAME}_api_test" "$APP_IMG_NAME:test" bash -c "adk api_server --host=0.0.0.0 && sleep 60"
    - sleep 10
    - docker exec "${APP_IMG_NAME}_api_test" curl -V http://0.0.0.0:8000/ || echo "Internal API test failed"
    - docker exec "${APP_IMG_NAME}_api_test" curl -V http://0.0.0.0:8000/docs/ || echo "Internal API docs test failed"
    - docker stop "${APP_IMG_NAME}_api_test" || true
    
    
    - echo "Unit tests completed"
    
  allow_failure: false
