version: '3.8'
services:
  google-adk:
    build:
      context: .
      dockerfile: Dockerfile
    image: $APP_IMG_NAME:$APP_IMG_TAG
    container_name: $APP_CONTAINER_NAME
    ports:
      - "8000:8000"           # API server port
      - "8501:8501"           # Streamlit port

    command: [tail, "-f", "/dev/null"]  # Keep the container running
    networks:
      - adk-network

networks:
  adk-network:
    driver: bridge
