version: '3.8'

services:
  google-adk:
    build:
      context: .
      dockerfile: Dockerfile
    image: google_adk:latest
    container_name: google-adk-workspace
    volumes:
      - .:/workspace
    command: tail -f /dev/null
    ports:
      - "8000:8000" 
      - "8501:8501"           # Expose Streamlit port
      - "8051:8051"
    #network_mode: "host"            # Expose app port
    networks:
      - adk-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"             # Expose MongoDB port
    networks:
      - adk-network                 
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
networks:
  adk-network:
    driver: bridge
