version: '3.8'

services:
  google-adk:
    build:
      context: .
      dockerfile: Dockerfile
    image: google_adk:latest
    container_name: "${APP_IMG_NAME}"
    # volumes:
    #   - .:/workspace
    ports:
      - "8000:8000" 
      - "8501:8501"           # Expose Streamlit port
      - "8051:8051"
    #network_mode: "host"            # Expose app port
    # networks:
    #   - adk-network
    depends_on:
      - mongodb
    command:
      - /bin/bash
      - -c
      - |
        adk api_server --host=0.0.0.0 --port=8000 &
        sleep 10
        streamlit run streamlit_app.py --server.address 0.0.0.0 --server.port 8501 || true
        wait

  mongodb:
    image: mongo:latest
    container_name: "${APP_DB_NAME}"
    restart: always
    ports:
      - "27017:27017"             # Expose MongoDB port
    # networks:
    #   - adk-network   
    # network_mode: "host" 
    # volumes:
    #   - ./mongodb:/tmp/mongodb  # Persist MongoDB data             
    command:
      - /bin/bash
      - -c
      - |
        mongod --replSet rs0 --bind_ip_all &
        sleep 10
        mongosh --eval "rs.initiate()" || true
        wait
    # tmpfs:
    #   - /data/db
networks:
  adk-network:
    driver: bridge
