version: '3.8'
services:
  google-adk:
    build:
      context: .
      dockerfile: Dockerfile
    image: google-adk:latest
    container_name: google-adk-container
    volumes:
    #   - mongodb_data:/data/db        # Uncomment to persist MongoDB data
      - .:/workspace                 # Uncomment for development
    ports:
      - "8000:8000"           # API server port
      - "8501:8501"           # Streamlit port
      - "27017:27017"         # MongoDB port
    environment:
      - MONGODB_URI=$MONGODB_URI 
      - API_URL=$API_URL
      - API_KEY=$API_KEY
      - API_HOST=$API_HOST
      - PROJECT_PATH=$PROJECT_PATH
      - FASTAPI_HOST=$FASTAPI_HOST
    # restart: unless-stopped
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    command: [tail, "-f", "/dev/null"]  # Keep the container running
    networks:
      - adk-network

# volumes:
#   mongodb_data:
#     driver: local

networks:
  adk-network:
    driver: bridge
